### ISSUE TITLE
ayuda con lahman

### ISSUE THREAD

**Issue by pachadotdev** [cienciadedatos/datos#101]
dejé un draft de las traducciones para relational data, eso si hay muchos términos de baseball que no entiendo y requiero ayuda en su traducción

**Comment by pachadotdev** [comment]
falta traducir 

- [ ] fielding InnOuts
- [ ] pitching Walks
- [ ] pitching Outs Pitched (innings pitched x 3)
- [ ] pitching IBB
- [ ] pitching HBP
- [ ] pitching Balks
- [x] pitching SH
- [x] pitching SF

**Comment by jbkunst** [comment]
Creo que acá podría ayudarnos @darh78 :) Le pediré ayuda :D.

**Comment by pachadotdev** [comment]
Thx!

**Comment by darh78** [comment]
Hola @jbkunst y @pachamaltese, cómo están? 
Claro que sí puedo echar una mano con esto, de hecho me gusta la idea.

¿Cuál es la dataframe de “Lahman” que están utilizando?, para contextualizar la lista de arriba.

Es importante decir que hay muchos términos en el Béisbol que no van a tener traducción al castellano, pero allí haré la cotación.

**Comment by jbkunst** [comment]
@darh78  Muchas gracias! 

Se está usando `Batting`, `Master`, y `Salaries`. Creo que la más relevante/difícil es `Batting` y algunos
campos/columnas de `Master` (que me corriga @pachamaltese en caso que me equivoque):

``` r
dplyr::glimpse(Lahman::Batting)
#> Observations: 105,861
#> Variables: 22
#> $ playerID <chr> "abercda01", "addybo01", "allisar01", "allisdo01", "a...
#> $ yearID   <int> 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871, 1871,...
#> $ stint    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
#> $ teamID   <fct> TRO, RC1, CL1, WS3, RC1, FW1, RC1, BS1, FW1, BS1, CL1...
#> $ lgID     <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
#> $ G        <int> 1, 25, 29, 27, 25, 12, 1, 31, 1, 18, 22, 1, 10, 3, 20...
#> $ AB       <int> 4, 118, 137, 133, 120, 49, 4, 157, 5, 86, 89, 3, 36, ...
#> $ R        <int> 0, 30, 28, 28, 29, 9, 0, 66, 1, 13, 18, 0, 6, 7, 24, ...
#> $ H        <int> 0, 32, 40, 44, 39, 11, 1, 63, 1, 13, 27, 0, 7, 6, 33,...
#> $ X2B      <int> 0, 6, 4, 10, 11, 2, 0, 10, 1, 2, 1, 0, 0, 0, 9, 3, 0,...
#> $ X3B      <int> 0, 0, 5, 2, 3, 1, 0, 9, 0, 1, 10, 0, 0, 0, 1, 3, 0, 0...
#> $ HR       <int> 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0,...
#> $ RBI      <int> 0, 13, 19, 27, 16, 5, 2, 34, 1, 11, 18, 0, 1, 5, 21, ...
#> $ SB       <int> 0, 8, 3, 1, 6, 0, 0, 11, 0, 1, 0, 0, 2, 2, 4, 4, 0, 0...
#> $ CS       <int> 0, 1, 1, 1, 2, 1, 0, 6, 0, 0, 1, 0, 0, 0, 0, 4, 0, 0,...
#> $ BB       <int> 0, 4, 2, 0, 2, 0, 1, 13, 0, 0, 3, 1, 2, 0, 2, 9, 0, 0...
#> $ SO       <int> 0, 0, 5, 2, 1, 1, 0, 1, 0, 0, 4, 0, 0, 0, 2, 2, 3, 0,...
#> $ IBB      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
#> $ HBP      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
#> $ SH       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
#> $ SF       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
#> $ GIDP     <int> 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0,...
```

<sup>Created on 2019-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pachadotdev** [comment]
Gracias! Son los mencionados y acá tengo los yml con las traducciones.
https://github.com/pachamaltese/datos/tree/master/inst/specs

Si buscas lo q falta de la lista en los yml, los encontrarás en inglés y
los demás ya están traducidos

**Comment by pachadotdev** [comment]
Batting ya está lista, a lo q menciona Joshua hay que agregarle fielding

**Comment by pachadotdev** [comment]
solucionado en 60ff3d58150b31e9f194326ac00300446e99d6be
