### ISSUE TITLE
problem with gapminder

### ISSUE THREAD

**Issue by pachadotdev** [cienciadedatos/datos#107]
When running `install.packages("datos")` in a fresh R installation on Windows, `gapminder` is not installed, but `datos` still installs but the table `paises` fails unless you type `install.packages("gapminder")`.
This did not happen during Dec, 2019 while we where in the middle of R4DS translation.

**Comment by rivaquiroga** [comment]
`datos` nunca ha instalado los paquetes que contienen los datasets a traducir. Es por eso que en la sección "Requisitos" se explica que es necesario instalarlos por separado: https://cienciadedatos.github.io/datos/

**Comment by pachadotdev** [comment]
> `datos` nunca ha instalado los paquetes que contienen los datasets a traducir. Es por eso que en la sección "Requisitos" se explica que es necesario instalarlos por separado: https://cienciadedatos.github.io/datos/

gracias!! me perdí esa parte que se movió a suggests
