### ISSUE TITLE
Should we fix "found XXX marked UTF-8 strings"

### ISSUE THREAD

**Issue by maurolepore** [cienciadedatos/datos#117]
@rivaquiroga and @pachamaltese, 

We see a note similar to this:

```
Version: 0.2.0
Check: data for non-ASCII characters
Result: NOTE
     Note: found 259 marked UTF-8 strings
Flavors: r-patched-solaris-x86, r-release-osx-x86_64, r-oldrel-osx-x86_64
```
-- [CRAN checks](https://cran-archive.r-project.org/web/checks/2020/2020-02-20_check_results_datos.html)

Have you seen it before? (I don't see that note in [cran-comments.md](https://github.com/cienciadedatos/datos/blob/master/cran-comments.md)). If so, how did you address it?

@jonkeane is helping me and he sees it in other packages so it might be fine:

> That one note might be fine, I see at least a few packages on CRAN that do have it as a note and they seem to be published just fine: ftp://stat.ethz.ch/pub/Software/R-CRAN/web/checks/check_results_isdparser.html

**Comment by rivaquiroga** [comment]
I've also seen that note before in other packages. We changed all the non-ASCII characters in the YAML files. Maybe these are the ones from the Readme :thinking:

**Comment by jonkeane** [comment]
I looked around a bit to see if I could find them or resolve this `NOTE`, it looks like those 259 are in the `frutas`, `oraciones`, and `palabras`. I've dug around in the r-devel list, and it mostly seems like the `NOTE` is ok on CRAN especially if there's a reason to have non ASCII characters.

And packages like tidyr seem to get away with it: https://cran.r-project.org/web/checks/check_results_tidyr.html

e.g. https://r.789695.n4.nabble.com/quot-found-4-marked-UTF-8-strings-quot-during-check-of-package-but-where-td4729560.html

**Comment by rivaquiroga** [comment]
I totally forgot about those datasets! Good catch.
So, it seems that we can leave them as they are. We do have a reason for having non ASCII characters

**Comment by maurolepore** [comment]
Thanks @jonkeane, 
Can you share  a snippet of the code you used to find the data with non ASCII characters?
It might help me explain in cran-comments.md why we believe the NOTE is fine. I don't think CRAN maintainers will have time to figure that out for themselves. 

If you don't mind I would leave this issue open for a bit longer until I have time to explore those data myself and think how I would convince a CRAN maintainer.

**Comment by rivaquiroga** [comment]
Those datasets are the spanish version of stringr::sentences, stringr::fruits and stringr::words. BTW, this NOTE was on the previous version of `datos` and CRAN was ok with it because of the aim of this package.
