### ISSUE TITLE
DOI for datos

### ISSUE THREAD

**Issue by rivaquiroga** [cienciadedatos/datos#125]
Once version `0.3` is released, I would like to add a DOI to this repository to make the code citable:  https://guides.github.com/activities/citable-code/

Any objections @pachamaltese, @maurolepore, @edgararuiz?

**Comment by pachadotdev** [comment]
I agree

**Comment by maurolepore** [comment]
Sounds great!

**Comment by rivaquiroga** [comment]
We will add the DOI through #139
