### ISSUE TITLE
Typo gapminder.yml

### ISSUE THREAD

**Issue by jbkunst** [cienciadedatos/datos#126]
Hola,

Detalle en Japón (dice Japén):
https://github.com/cienciadedatos/datos/blob/master/inst/specs/gapminder.yml#L74

![image](https://user-images.githubusercontent.com/56481/81952225-3a2f3880-95d4-11ea-8cf1-d9ba2390a98f.png)

Hasta ahora es el único que pude encontrar.

Saludos,

**Comment by rivaquiroga** [comment]
GRACIAS!!!! Sabía que había visto un typo en un nombre de país, pero no me acordaba cuál era.
