### ISSUE TITLE
Ayuda para mpg

### ISSUE THREAD

**Issue by edgararuiz-zz** [cienciadedatos/datos#14]
Necesitamos la seccion de ayuda para el spec `mpg.yml`:
https://github.com/cienciadedatos/datos/blob/master/inst/specs/mpg.yml

Usando este patron:
https://github.com/cienciadedatos/datos/blob/master/inst/specs/diamonds.yml

Por favor note que cada variable va a necesitar tambien una seccion que se llama `desc`

**Comment by maurolepore** [comment]
Add a GitHub URL to DESCRIPTION to help browse pull requests from the console. Now this link is missing.

```R
> browse_github_pulls()
✔ Setting active project to 'C:/Users/LeporeM/Documents/Dropbox/git/ml/datos'
Error: Package does not provide a GitHub URL.
Call `rlang::last_error()` to see a backtrace
```
