### ISSUE TITLE
tramo de edad erróneo en dataset OMS

### ISSUE THREAD

**Issue by pachadotdev** [cienciadedatos/datos#145]
El dataset OMS tenía un error en mi traducción inicial. El tramo 35-44 estaba como 35-34 en castellano. Lo he corregido en 6fcea4d.

**Comment by pachadotdev** [comment]
@rivaquiroga holi, esto es relevante para la próxima versión que se envíe a CRAN

**Comment by rivaquiroga** [comment]
@pachamaltese, ya lo agregué a NEWS.md :heavy_check_mark:

**Comment by pachadotdev** [comment]
> @pachamaltese, ya lo agregué a NEWS.md heavy_check_mark

sorry, no caché que usamos uso, que top !!!
