### ISSUE TITLE
Error nombres variables datos oms

### ISSUE THREAD

**Issue by luifrancgom** [cienciadedatos/datos#149]
Cordial saludo 

En el conjunto de datos `oms` todas las variables que contienen el rango de edad de 35 a 44 años terminan en 35**3**4 donde deberían terminar en 35**4**4. Esto se presenta en la version 0.3.0

Esta parte es importante corregirla dado que se utiliza en la sección `12.6 Estudio de caso` de R para ciencia de datos.

**Comment by rivaquiroga** [comment]
¡Hola, @luifrancgom!
En la versión en desarrollo del paquete ese error ya está resuelto. Puedes instalarla con `remotes::install_github("cienciadedatos/datos")`. Esperamos re-enviar pronto el paquete a CRAN, para que ese cambio quede reflejado también ahí.
