### ISSUE TITLE
columna especies de data frame `flores`

### ISSUE THREAD

**Issue by jbkunst** [cienciadedatos/datos#151]
Hola!

Generalmente el nombre de las columnas es singular, por lo mismo creo que la traducción  del campo `Species` de `iris` debiese ser `Especie` en https://github.com/cienciadedatos/datos/blob/master/inst/specs/iris.yml#L18

Adicionalmente, existe fecha para actualizar el paquete en CRAN?  Coincidió que quería utilizar `pinguinos` para una clase y veo que solamente está en la versión de desarrollo.

Un abrazo,

**Comment by rivaquiroga** [comment]
Toda la razón. El único problema de actualizarlo a estas alturas es que si cambiamos el nombre de la variable le podríamos romper el código a toda la gente que lo puso en plural. @pachadotdev, ¿qué opinas? ¿lo cambiamos? ¿o lo dejamos tal cual?

**Comment by pachadotdev** [comment]
> Toda la razón. El único problema de actualizarlo a estas alturas es que si cambiamos el nombre de la variable le podríamos romper el código a toda la gente que lo puso en plural. @pachadotdev, ¿qué opinas? ¿lo cambiamos? ¿o lo dejamos tal cual?

yo creo que habria que corregirlo y agregar una nota en NEWS.md
lo adecuado es usar correctamente el castellano, o sino caemos en cosas como decir "me entendisteS?"

**Comment by rivaquiroga** [comment]
Listo el cambio!

**Comment by rivaquiroga** [comment]
@jbkunst, respecto de la otra pregunta, la nueva versión del paquete va camino a CRAN.
