### ISSUE TITLE
Pre PR: Agregando nuevos datos

### ISSUE THREAD

**Issue by jbkunst** [cienciadedatos/datos#153]
Hola,

Agradecer a este paquete, ha ayudado mucho en clases 😍🙌.

Abro este issue pues pretendo hacer un PR para agregar nuevos datos, pero requiere de una **pequeña modificación**.

### Acerca de la modificación

En un comienzo deseo agregar al menos 2 dataset del paquete https://github.com/tidymodels/modeldata que aparecen en https://github.com/tidymodels/TMwR, los cuales son `ames` https://www.tmwr.org/ames.html y `credit_data`.

Sin embargo, para esto hay que hacer un leve cambio dado que en el paquete `{modeldata}` (y en otros) la definición de los datos en `R\data.R` termina con `NULL` y no con el nombre de los datos en formato string:

- En modeldata al terminar el bloque de descripción de los datos usando comentarios roxygen aparece un `NULL`. https://github.com/tidymodels/modeldata/blob/main/R/ames.R#L26.
- En caso contrario, (los datos que actualmente utiliza el paquete datos) terminan indicando el nombre en formato string: https://github.com/hadley/babynames/blob/master/R/data.R#L13.

Lo mismo, pero de otra forma 😊:

```r
#' En algunos paquetes terminan con NULL
#' @format A data frame with f...
NULL

#' En otros, los que utiliza el paque datos..
#' @format A data frame with f...
"babynames"
```

Lo anterior produce que en el primer caso no se pueda acceder a los datos utilizando `paquete::losdatos` a diferencia del primero (en el paquete datos por tanto puede hacer uso de ` eval(parse(text = "babynames::babynames"))` en la segunda casuisitica).

Por lo anterior he creado una pequeña función que dado el paquete y los datos (en formato `"modeldata::credit_data"`) retorna el data frame en cuestión https://github.com/jbkunst/datos/blob/main/R/translate.R#L79. Con lo anterior se **modificaría** 2 líneas: 1 en la funcion `translate`, otra en un test para obtener el data frame original cuando se realiza la comparación y no estoy seguro si en otra parte.

### Helpers para comenzar una traducción

Adicionalmente, he creado una función [`create_skeleton_translation`](https://github.com/jbkunst/datos/blob/main/R/translate.R#L106)  que  que dado una especificación de source (como por ejemplo `"modeldata::credit_data"`) genera un archivo yml temporal y se abre en rstudio (con `{rstudioapi}`) para comenzar la traducción el cual ya contiene todos los nombres, campos (y niveles si es que es factor/string) y detalles para completar.

### Terminando...

Me gustaría tener feedback de ustedes para saber si aceptarían eventualmente estas traducciones: 2 data frames, y 2 dependencias más, el paquete `{modeldata}` y `{rstudioapi}`[^1]  ; y por tanto conocer si tiene sentido compartir la funcionalidad que implementé.

Eso, quedo atento a vuestra respuesta! Saludos, que estén muy bien!!

[^1]: En términos de depedencias adicionales: `{rstudioapi}` es liviano, y en su caso `{modeldata}` agregaría `{purrr}` solamente (pues dplyr, rlang, el paquete datos ya los tiene) https://github.com/rstudio/rstudioapi/blob/main/DESCRIPTION#L1 https://github.com/tidymodels/modeldata/blob/main/DESCRIPTION#L1

**Comment by rivaquiroga** [comment]
¡Hola, @jbkunst! Muchas gracias :) Lo de los helpers está buenísimo!
Voy a revisar lo que comentas de los datos que terminan en `NULL`. En la versión en portugués de este paquete ([dados](https://cienciadedatos.github.io/dados/reference/casas.html)) están traducidos los datos de Ames desde la versión del paquete [AmesHousing](https://github.com/topepo/AmesHousing). No sé si es exactamente el mismo dataset, pero ahí [también termina en NULL](https://github.com/topepo/AmesHousing/blob/master/R/ames_raw.R) y sí se puede usar `paquete::losdatos`, tanto en el original como en la traducción.

**Comment by jbkunst** [comment]
Hola @rivaquiroga, gracias por a respuesta!

Tiene razón respecto al `NULL`, esa no es la razón 😅. Estoy comparando los repositorios de AmesHouse y modeldata pero no encuentro de momento la diferencia del porque no se puede agregar dataset desde modeldata (ver reprex al final).

Por otro lado, al parecer son los mismos datos con diferencias en los nombres (en modeldata, los campos no poseen espacios) y los tipos de columnas chr/fct. Si bien podría intentar por ese lado, como comenté anteriormente, quería agregar otros datasets desde modeldata para tener datos que se orientados al modelamiento predictivo.

``` r
library(AmesHousing)
library(modeldata)

# AmesHousing 
AmesHousing::ames_raw
#> # A tibble: 2,930 × 82
#>    Order PID    `MS SubClass` `MS Zoning` `Lot Frontage` `Lot Area` Street Alley
#>    <int> <chr>  <chr>         <chr>                <int>      <int> <chr>  <chr>
#>  1     1 05263… 020           RL                     141      31770 Pave   <NA> 
#>  2     2 05263… 020           RH                      80      11622 Pave   <NA> 
#>  3     3 05263… 020           RL                      81      14267 Pave   <NA> 
#>  4     4 05263… 020           RL                      93      11160 Pave   <NA> 
#>  5     5 05271… 060           RL                      74      13830 Pave   <NA> 
#>  6     6 05271… 060           RL                      78       9978 Pave   <NA> 
#>  7     7 05271… 120           RL                      41       4920 Pave   <NA> 
#>  8     8 05271… 120           RL                      43       5005 Pave   <NA> 
#>  9     9 05271… 120           RL                      39       5389 Pave   <NA> 
#> 10    10 05271… 060           RL                      60       7500 Pave   <NA> 
#> # … with 2,920 more rows, and 74 more variables: `Lot Shape` <chr>,
#> #   `Land Contour` <chr>, Utilities <chr>, `Lot Config` <chr>,
#> #   `Land Slope` <chr>, Neighborhood <chr>, `Condition 1` <chr>,
#> #   `Condition 2` <chr>, `Bldg Type` <chr>, `House Style` <chr>,
#> #   `Overall Qual` <int>, `Overall Cond` <int>, `Year Built` <int>,
#> #   `Year Remod/Add` <int>, `Roof Style` <chr>, `Roof Matl` <chr>,
#> #   `Exterior 1st` <chr>, `Exterior 2nd` <chr>, `Mas Vnr Type` <chr>, …

source <- "AmesHousing::ames_geo"

suppressWarnings(eval(parse(text = source)))
#> # A tibble: 2,932 × 3
#>    PID        Longitude Latitude
#>    <chr>          <dbl>    <dbl>
#>  1 0526301100     -93.6     42.1
#>  2 0526350040     -93.6     42.1
#>  3 0526351010     -93.6     42.1
#>  4 0526353030     -93.6     42.1
#>  5 0527105010     -93.6     42.1
#>  6 0527105030     -93.6     42.1
#>  7 0527127150     -93.6     42.1
#>  8 0527145080     -93.6     42.1
#>  9 0527146030     -93.6     42.1
#> 10 0527162130     -93.6     42.1
#> # … with 2,922 more rows

# modeldata
modeldata::ames
#> Error: 'ames' is not an exported object from 'namespace:modeldata'

source <- "modeldata::ames"

suppressWarnings(eval(parse(text = source)))
#> Error: 'ames' is not an exported object from 'namespace:modeldata'
```

<sup>Created on 2022-05-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rivaquiroga** [comment]
También me parece mejor que sean los de {modeldata}. Como señalas, podríamos traducir otros sets de datos de ahí mismo.
Tampoco me queda claro por qué no deja usar `modeldata::` 🤔. Quizás estaría bueno abrir un issue en el repo del paquete.

**Comment by jbkunst** [comment]
Se ha creado el issue https://github.com/tidymodels/modeldata/issues/44, te cuento apenas respondan.

Crees que es muy viable/complicada la _modificación_ que se menciona al comienzo del script? Creo que `get_data_from_df_source ` es una forma más robusta que hacer lo mismo que `eval` + `parse`. Lo menciono por que pueden existir eventualmente otros paquetes que presenten esta _característica_.

De todas formas, si se _corrige_ modeldata, yo feliz por el momento 👌😂.

**Comment by jbkunst** [comment]
Era el `LazyData: true`! El cambio vendrá en el próximo release por lo que ya no se requiere la función.

Por lo anterior, te parece entonces que el(los) PR(s) sean con las propuestas de traducciones y dos _helpers_ ? Las funciones que he estado utilizando de forma interna son:

- `create_skeleton_translation` para crear archivo yml con los campos requeridos para una traducción.
- `validate_translation` Una función para corregir y validar el archivo `specs.yml` reemplazando las letras con tilde (áéíóúÁÉÍÓÚñÑÜü) con su respectivo `"\u00.."`. (Si tienes mejores nombres... mejor!).

Saludos, que estés muy muy bien!
