### ISSUE TITLE
Traducir Lahman::Batting

### ISSUE THREAD

**Issue by edgararuiz-zz** [cienciadedatos/datos#22]

**Comment by rivaquiroga** [comment]
Antes del viernes dejo esto listo.

**Comment by pachadotdev** [comment]
@rivaquiroga ¿cómo vas con este? ahora mismo tengo media hora libre

**Comment by rivaquiroga** [comment]
Justo estaba trabajando en eso. Si me surje alguna duda, te aviso :baseball:

**Comment by pachadotdev** [comment]
perfecto!

**Comment by rivaquiroga** [comment]
Traducción de Lahman::Batting
[bateadores.txt](https://github.com/cienciadedatos/datos/files/2321146/bateadores.txt)

**Comment by pachadotdev** [comment]
Hola. Lo agrego al paquete datos?

**Comment by edgararuiz-zz** [comment]
Fixed with 10b0764834aab132300e4ae68ec2843a07d3d5f5
