### ISSUE TITLE
Traducir mtcars {datasets}

### ISSUE THREAD

**Issue by d4tagirl** [cienciadedatos/datos#24]
En el capítulo "Many models" se usa este dataset.

**Comment by d4tagirl** [comment]
Hecho el PR con el yaml para traducir `mtcars` en
cienciadedatos/datos#26

**Comment by edgararuiz-zz** [comment]
Fixed with https://github.com/cienciadedatos/datos/commit/c06f8cd3369c38d4f1c2e41bc6c444e73de1d65c
