### ISSUE TITLE
Convertir a tibble los datos de gapminder (dataset paises)

### ISSUE THREAD

**Issue by d4tagirl** [cienciadedatos/datos#25]
En el capítulo "Many Models" se explora el dataset poniendo directamente `gapminder`, porque es un tibble. Como `paises` es un data frame, cuando pongo `paises` imprime _todas_ las filas. Me parece más prolijo cambiar el dataset que escribir `as.tibble(paises)`, pero podría también dejarlo así.

**Comment by edgararuiz-zz** [comment]
Gracias @d4tagirl , este cambio lo tengo que hacer en el paquete que ejecuta la traduccion. Abri un Issue en el repo.

**Comment by edgararuiz-zz** [comment]
@d4tagirl - Puedes probar la nueva version de `datos`? Por alguna razon, ahora esta class `tbl`, pero cuando imprime en my computadora, imprime como `data.frame`, no se si eso va a ser un problema en tus ejemplos

**Comment by d4tagirl** [comment]
Ahora me lo imprime como `tibble`, así que ya quedó [cambiado en el PR](https://github.com/cienciadedatos/r4ds/pull/10)! Muchas gracias!

**Comment by edgararuiz-zz** [comment]
Perfecto! Cerrando este Issue
