### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by maurolepore** [cienciadedatos/datos#33]
Possibly useful badges include experimental, cran, travis, ...

**Comment by raynamharris** [comment]
This repo doesn't have travis integration setup, so adding a build badge doesn't make sense... see 
https://travis-ci.org/cienciadedatos/datos

**Comment by pachadotdev** [comment]
@raynamharris adding them now :)

**Comment by maurolepore** [comment]
Thanks @pachamaltese! I see that `.travis.yml` is now there and also that it has quite a bit of content, some of which is not used right now. For example, right now we have no test this code isn't used:

```
after_success:
  - Rscript -e 'library(covr);codecov()'
```

Do you prefer to leave this as a reminder to add something later or do you prefer to remove it now and add it later if we need it?

**Comment by pachadotdev** [comment]
That is a reminder to go against my lazyness :)
I shall add code coverage ASAP
