### ISSUE TITLE
Add pkgdown website

### ISSUE THREAD

**Issue by maurolepore** [cienciadedatos/datos#34]

**Comment by raynamharris** [comment]
Clarification, use pkgdown to create a website.

I'll tackle this one

**Comment by maurolepore** [comment]
Step 1: `usethis::use_pkgdown()`
Step 2: `pkgdown::build_site()`
Step 3: Someone with admin privilege should go to Settings/GitHub Pages and activate page using master/docs

**Comment by maurolepore** [comment]
I think @raynamharris intended to close this via #42. Closing manually.
