### ISSUE TITLE
Add examples section

### ISSUE THREAD

**Issue by edgararuiz-zz** [cienciadedatos/datos#47]
The plan is to first see if we can have `datalang` use the same examples from the original package. If not we may need to make a change yaml structure

cc @maurolepore

**Comment by pachadotdev** [comment]
@edgararuiz ¿cómo seguimos con esto? ha habido varios cambios de disenio respecto al plan original de `datos`  tenemos ejemplos acá https://cienciadedatos.github.io/datos/
