### ISSUE TITLE
Add the dataset stringr::sentences

### ISSUE THREAD

**Issue by maurolepore** [cienciadedatos/datos#54]
Just a reminder that `stringr::sentences` has not yet been added to data/ (despite #43). There are already may datasets in data/ -- suggesting there is a procedure already in place. Is there anything I can do?
I would add the following line in data-raw/data.R

```
oraciones <- stringr::sentences
usethis::use_data(oraciones, overwrite = TRUE) 
```

And I would do that for all datasets. That way data-raw/data.R clearly shows where each dataset comes from and the data is efficiently compressed during save into data/.

**Comment by rivaquiroga** [comment]
Al parecer no se han agregado porque no estaban traducidas las oraciones que componen ese dataset
