### ISSUE TITLE
estructura  de `mtautos`

### ISSUE THREAD

**Issue by rivaquiroga** [cienciadedatos/datos#78]
¡Hola! 
En `mtautos` se pierden los nombres de los modelos de los autos porque en `mtcars` no están guardados en una columna. Eso hace que:
```
select(mtcars, mpg, cyl, disp) %>% 
  head()
```
tenga un output distinto que:
```
select(mtautos, millas, cilindros, cilindrada) %>% 
  head()
```

**Comment by jbkunst** [comment]
Otro caso de uso:

``` r
c <- cor(mtcars)
c <- cor(datos::mtautos)
#> Error in cor(datos::mtautos): 'x' must be numeric
```

<sup>Created on 2019-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pachadotdev** [comment]
@jbkunst como usamos tibbles para seguir tidy data, con `cor(datos::mtautos %>% select(-modelo))` funciona

**Comment by edgararuiz-zz** [comment]
Ahora si, fixed b1282b153f555deb49cb3c0fdf36c3aa1301ec9d
