### ISSUE TITLE
Sección "Actualización del paquete"

### ISSUE THREAD

**Issue by jbkunst** [cienciadedatos/datos#95]
Hola 😄 !

La sección de "Actualización del paquete" (1) en el `README.md` me parece que es más para desarrolladores que para usuarios, ¿cierto? En ese caso puede que sea mejor dejarlo en otra parte. 

1: https://github.com/cienciadedatos/datos#actualizaci%C3%B3n-del-paquete

**Comment by edgararuiz-zz** [comment]
100% correcto.  Ese código es para que yo me acuerde como actualizar el paquete :) 

Lo planeo remover en una versión en el futuro
