### ISSUE TITLE
Suggest e Imports

### ISSUE THREAD

**Issue by jbkunst** [cienciadedatos/datos#96]
Hola, vengo con más dudas 😅 

1. En un ambiente limpo (rstudio.cloud) instalo tidyverse y datos, todo ok 😄.
2. Quiero usar los datos `datos::vehiculos` los cuales no encontró dado que no existía la dependencia `fueleconomy` pues no estaba en los `Imports`.
3. Vi que estaba en los `Suggest` junto a otros, por lo que ingenuamente intenté `install.packages("datos", dependencies = "Suggests")`
4. Pero, pero, peeero no noté que en dicha lista existían `testthat` y `covr`  y comenzó con a instalar una gran lista de paquetes que no necesito, ni tampoco deseo descargarlos.

Dado que que estos dos últimos son -de forma general- para desarrolladores , creen que es mejor removerlos del suggest? O en su alternativa, cambiar todo lo referente de paquete de datos a imports?

**Comment by edgararuiz-zz** [comment]
Pase un buen tiempo decidiendo donde listar cada paquete en DESCRIPTION.  No se si hay alguna alternativa mejor en como listarlos.  Pienso que la solucion será ver si podemos agregar un chequeo en la función que traduce los datos originales, y que diera un error más específico de instalar el paquete que necesita.

**Comment by jbkunst** [comment]
Gracias por la respuesta, te entiendo completamente.

Estoy al tanto que muchos paquetes del tidyverse contienen dichos paquetes en el suggest. Mi pregunta es: ¿para que se le sugiere al usuario "final" (al no desarrollador, por ejemplo) esos paquetes? Quizás es darle mucha vuelta, pero es mi inocente pregunta. 

Gracias nuevamente por tu rápida respuesta 😃!

**Comment by pachadotdev** [comment]
@edgararuiz @jbkunst ¿qué les parece agregar algo del tipo `pacman::p_load(Lahman,etc...)`?

**Comment by jbkunst** [comment]
@pachamaltese 

En lo personal no me agrada mucho `pacman` como parte de un paquete, creo está orientado la uso _interactivo_.

**Comment by pachadotdev** [comment]
@jbkunst entonces algo así en el código después del mensaje al inicio

```r
list_of_packages <- c("Lahman", "fueleconomy", "etc")
new_packages <- list.of.packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)
```

**Comment by rivaquiroga** [comment]
@jbkunst, acabamos de cambiar esto en https://github.com/cienciadedatos/datos/pull/111. Finalmente movimos los paquetes a Imports, sobre todo porque simplifica el uso del paquete cuando se hace clases a personas que recién están empezando a utilizar R.
